//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AICPA.Destroyer.netForumServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.avectra.com/2005/", ConfigurationName="netForumServices.AICPAOPLWSSoap")]
    public interface AICPAOPLWSSoap {
        
        // CODEGEN: Generating message contract since message AICPAGetOPLSubscriptionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avectra.com/2005/AICPAGetOPLSubscriptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AICPA.Destroyer.netForumServices.AICPAGetOPLSubscriptionsResponse AICPAGetOPLSubscriptions(AICPA.Destroyer.netForumServices.AICPAGetOPLSubscriptionsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avectra.com/2005/")]
    public partial class AuthorizationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AICPAGetOPLSubscriptions", WrapperNamespace="http://www.avectra.com/2005/", IsWrapped=true)]
    public partial class AICPAGetOPLSubscriptionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.avectra.com/2005/")]
        public AICPA.Destroyer.netForumServices.AuthorizationToken AuthorizationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.avectra.com/2005/", Order=0)]
        public string EncryptedCustomerKey;
        
        public AICPAGetOPLSubscriptionsRequest() {
        }
        
        public AICPAGetOPLSubscriptionsRequest(AICPA.Destroyer.netForumServices.AuthorizationToken AuthorizationToken, string EncryptedCustomerKey) {
            this.AuthorizationToken = AuthorizationToken;
            this.EncryptedCustomerKey = EncryptedCustomerKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AICPAGetOPLSubscriptionsResponse", WrapperNamespace="http://www.avectra.com/2005/", IsWrapped=true)]
    public partial class AICPAGetOPLSubscriptionsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.avectra.com/2005/")]
        public AICPA.Destroyer.netForumServices.AuthorizationToken AuthorizationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.avectra.com/2005/", Order=0)]
        public System.Xml.XmlNode AICPAGetOPLSubscriptionsResult;
        
        public AICPAGetOPLSubscriptionsResponse() {
        }
        
        public AICPAGetOPLSubscriptionsResponse(AICPA.Destroyer.netForumServices.AuthorizationToken AuthorizationToken, System.Xml.XmlNode AICPAGetOPLSubscriptionsResult) {
            this.AuthorizationToken = AuthorizationToken;
            this.AICPAGetOPLSubscriptionsResult = AICPAGetOPLSubscriptionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AICPAOPLWSSoapChannel : AICPA.Destroyer.netForumServices.AICPAOPLWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AICPAOPLWSSoapClient : System.ServiceModel.ClientBase<AICPA.Destroyer.netForumServices.AICPAOPLWSSoap>, AICPA.Destroyer.netForumServices.AICPAOPLWSSoap {
        
        public AICPAOPLWSSoapClient() {
        }
        
        public AICPAOPLWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AICPAOPLWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AICPAOPLWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AICPAOPLWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AICPA.Destroyer.netForumServices.AICPAGetOPLSubscriptionsResponse AICPA.Destroyer.netForumServices.AICPAOPLWSSoap.AICPAGetOPLSubscriptions(AICPA.Destroyer.netForumServices.AICPAGetOPLSubscriptionsRequest request) {
            return base.Channel.AICPAGetOPLSubscriptions(request);
        }
        
        public System.Xml.XmlNode AICPAGetOPLSubscriptions(ref AICPA.Destroyer.netForumServices.AuthorizationToken AuthorizationToken, string EncryptedCustomerKey) {
            AICPA.Destroyer.netForumServices.AICPAGetOPLSubscriptionsRequest inValue = new AICPA.Destroyer.netForumServices.AICPAGetOPLSubscriptionsRequest();
            inValue.AuthorizationToken = AuthorizationToken;
            inValue.EncryptedCustomerKey = EncryptedCustomerKey;
            AICPA.Destroyer.netForumServices.AICPAGetOPLSubscriptionsResponse retVal = ((AICPA.Destroyer.netForumServices.AICPAOPLWSSoap)(this)).AICPAGetOPLSubscriptions(inValue);
            AuthorizationToken = retVal.AuthorizationToken;
            return retVal.AICPAGetOPLSubscriptionsResult;
        }
    }
}
